/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as MedallionRouteImport } from './routes/medallion'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as PayReferenceRouteImport } from './routes/pay.$reference'
import { Route as OrderConfirmedReferenceRouteImport } from './routes/order-confirmed.$reference'
import { Route as ApiPublicPayshapWebhookRouteImport } from './routes/api/public/payshap-webhook'

const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const MedallionRoute = MedallionRouteImport.update({
  id: '/medallion',
  path: '/medallion',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayReferenceRoute = PayReferenceRouteImport.update({
  id: '/pay/$reference',
  path: '/pay/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedReferenceRoute = OrderConfirmedReferenceRouteImport.update({
  id: '/order-confirmed/$reference',
  path: '/order-confirmed/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayshapWebhookRoute = ApiPublicPayshapWebhookRouteImport.update({
  id: '/api/public/payshap-webhook',
  path: '/api/public/payshap-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/medallion': typeof MedallionRoute
  '/shipping': typeof ShippingRoute
  '/order-confirmed/$reference': typeof OrderConfirmedReferenceRoute
  '/pay/$reference': typeof PayReferenceRoute
  '/shop/$id': typeof ShopIdRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/payshap-webhook': typeof ApiPublicPayshapWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/medallion': typeof MedallionRoute
  '/shipping': typeof ShippingRoute
  '/order-confirmed/$reference': typeof OrderConfirmedReferenceRoute
  '/pay/$reference': typeof PayReferenceRoute
  '/shop/$id': typeof ShopIdRoute
  '/shop': typeof ShopIndexRoute
  '/api/public/payshap-webhook': typeof ApiPublicPayshapWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/medallion': typeof MedallionRoute
  '/shipping': typeof ShippingRoute
  '/order-confirmed/$reference': typeof OrderConfirmedReferenceRoute
  '/pay/$reference': typeof PayReferenceRoute
  '/shop/$id': typeof ShopIdRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/payshap-webhook': typeof ApiPublicPayshapWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/medallion'
    | '/shipping'
    | '/order-confirmed/$reference'
    | '/pay/$reference'
    | '/shop/$id'
    | '/shop/'
    | '/api/public/payshap-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/medallion'
    | '/shipping'
    | '/order-confirmed/$reference'
    | '/pay/$reference'
    | '/shop/$id'
    | '/shop'
    | '/api/public/payshap-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/medallion'
    | '/shipping'
    | '/order-confirmed/$reference'
    | '/pay/$reference'
    | '/shop/$id'
    | '/shop/'
    | '/api/public/payshap-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MedallionRoute: typeof MedallionRoute
  ShippingRoute: typeof ShippingRoute
  OrderConfirmedReferenceRoute: typeof OrderConfirmedReferenceRoute
  PayReferenceRoute: typeof PayReferenceRoute
  ShopIdRoute: typeof ShopIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiPublicPayshapWebhookRoute: typeof ApiPublicPayshapWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medallion': {
      id: '/medallion'
      path: '/medallion'
      fullPath: '/medallion'
      preLoaderRoute: typeof MedallionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$reference': {
      id: '/pay/$reference'
      path: '/pay/$reference'
      fullPath: '/pay/$reference'
      preLoaderRoute: typeof PayReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed/$reference': {
      id: '/order-confirmed/$reference'
      path: '/order-confirmed/$reference'
      fullPath: '/order-confirmed/$reference'
      preLoaderRoute: typeof OrderConfirmedReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payshap-webhook': {
      id: '/api/public/payshap-webhook'
      path: '/api/public/payshap-webhook'
      fullPath: '/api/public/payshap-webhook'
      preLoaderRoute: typeof ApiPublicPayshapWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MedallionRoute: MedallionRoute,
  ShippingRoute: ShippingRoute,
  OrderConfirmedReferenceRoute: OrderConfirmedReferenceRoute,
  PayReferenceRoute: PayReferenceRoute,
  ShopIdRoute: ShopIdRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiPublicPayshapWebhookRoute: ApiPublicPayshapWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
